fix: Correct RetireJS analyzer configuration syntax
Error: Cannot find 'enabled' in class org.owasp.dependencycheck.maven.Retirejs

Wrong syntax:
<retirejs>
  <enabled>false</enabled>
</retirejs>

Correct syntax:
<retireJsAnalyzerEnabled>false</retireJsAnalyzerEnabled>
<nodeAnalyzerEnabled>false</nodeAnalyzerEnabled>

Also disabled Node.js analyzer since we're scanning Java services.